### PR TITLE
#307: Improve request logging

### PR DESCRIPTION
**Pull request by bonkey**
#307: Improve request logging

### CODE REVIEW

**Comment by bonkey** [comment]
@hani-ibrahim From Poland with Love

**Comment by hani-ibrahim** [comment]
b991a163a5a78db192c0b8696bc3580a
.
.
.
But 😆, I don't see the logs. and I can't find the `Live API` scheme

**Comment by bonkey** [comment]
@hani-ibrahim Don't know how it could be possible. The scheme is shared, and it's copied from AtlasDemo, and I've checked – it has Debug configuration used to run, and yes – it shows me logs, that's how I checked in both schemes if mocked service is starting only in one.

**Comment by bonkey** [comment]
👍

**Comment by hani-ibrahim** [comment]
weird! ... now appeared

**Comment by hani-ibrahim** [comment]
👍

**Pull request merged**
