### PR TITLE
Release 0.0.4

### PR DESCRIPTION
**Pull request by bonkey**
Not sure if I did it correctly, but just run manually commands from `pod.rb` (because `pod lib lint` doesn't work on my machine now.

### CODE REVIEW

**Comment by bonkey** [comment]
👍

**Comment by hani-ibrahim** [comment]
why 0.0.4?

**Comment by bonkey** [comment]
@hani-ibrahim because the former was 0.0.3? 👹 I simply increased it.

**Comment by hani-ibrahim** [comment]
Aha, I saw it was 1.0.0 in the project settings before updating and didn't see the the pod settings 

screen shot 2016-09-27 at 12 47 31 pm

**Comment by hani-ibrahim** [comment]
👍

**Comment by bonkey** [comment]
Well, it wasn't updated there

**Pull request merged**
