### PR TITLE
#17: Introduced translations through instance localizer

### PR DESCRIPTION
**Pull request by bonkey**
- Changed AtlasCheckout to class
- Removed String.loc
- Simplified CheckoutViewModel

(don't know why there're more commits...)

### CODE REVIEW

**Comment by bonkey** [comment]
For review only this commit counts: https://github.com/zalando-incubator/atlas-ios/pull/99/commits/843139adb1c69a7daaf15ede9d7d6f01b992ea4b

**Comment by bonkey** [comment]
👍

**Comment by bonkey** [comment]
+1 Approve

**Comment by bonkey** [comment]
👍

**Comment by ahmed-shehata** [comment]
👍

**Pull request merged**
