### PR TITLE
#700: Quick try to switch to git-lfs

### PR DESCRIPTION
**Pull request by bonkey**
Another try, as I saw it has support in Tower, so it was quick clickety-click to see if it works.

@hani-eloksh - could you check out this version and see if it has correct binaries on your local machine?

### CODE REVIEW

**Comment by hani-ibrahim** [comment]
tried to run the app but got this error

screen shot 2017-02-02 at 10 32 11 am

Then I tried `brew install git-lfs` but it gave me the same errors
Then I tried `git lfs install` which I took from the travis file but I got 
```
The filter.lfs.smudge attribute should be "git-lfs smudge -- %f" but is "git-lfs smudge %f"
Run `git lfs install --force` to reset git config.
``` 

Then I just run `./calypso.rb deps build` and it worked fine 👍

**Comment by hani-ibrahim** [comment]
👍

**Comment by bonkey** [comment]
But using `calypso deps build` is not the way to go, as you override those files, which sit as references, and should be replaced by git-lfs to binaries.

Let sit over it on Friday.

**Comment by bonkey** [comment]
👍

**Comment by bonkey** [comment]
Closing it right away. Finally everything worked, but the pricing model for LFS, even on open source is a blocker here.

**Pull request closed without merging**
