### PR TITLE
#711: Updated CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by bonkey**
Nothing fancy. I could push it directly, but I was too lazy to switch settings ;-)

### CODE REVIEW

**Comment by hani-ibrahim** [comment]
👍

**Comment by bonkey** [comment]
👍

**Comment by bonkey** [comment]
👍

**Comment by hani-ibrahim** [comment]
👍

**Comment by bonkey** [comment]
Both 👍  are here, zappr doesn't see it, too bad for zappr. Merging.

**Pull request merged**
