### PR TITLE
Fix + refactor for delivery date

### PR DESCRIPTION
**Pull request by bonkey**
- Fixed erliest key in Delivery
- Simplified delivery date formatting

### CODE REVIEW

**Comment by ahmed-shehata** [comment]
👍

**Comment by bonkey** [comment]
@hani-ibrahim btw. I wouldn't find this monster without this – in your opinion – not necessary line length limit.

**Comment by bonkey** [comment]
👍

**Comment by hani-ibrahim** [comment]
but how did you find this line since there are no warnings because of it?

**Comment by ahmed-shehata** [comment]
@hani-ibrahim  
You don't get the @bonkey title so easily.. 
image

**Comment by bonkey** [comment]
@hani-ibrahim Maybe you don't have them on for the whole workspace?

`File / Workspace Settings... -> Show all issues`

**Pull request merged**
