### PR TITLE
Issue 119 - Handle if user does not have default shipping/billing addresses

### PR DESCRIPTION
**Pull request by ahmed-shehata**
Issue #119 - Handle if user does not have default shipping/billing addresses

Notes:
- User will still be able to see the checkout screen (passed by an empty checkout object) instead of throwing an error (when no addresses are found)

- Address list is now checked before creating the checkout object, if empty will pass an empty checkout object (similar to the one when logged out)

### CODE REVIEW

**Comment by bonkey** [comment]
👍

**Comment by hani-ibrahim** [comment]
👍

**Comment by bonkey** [comment]
@ahmed-shehata where are the tests? ;-)

**Comment by bonkey** [comment]
👍

**Comment by ahmed-shehata** [comment]
👍

**Pull request merged**
