### PR TITLE
#655: Fixing unit tests

### PR DESCRIPTION
**Pull request by hani-ibrahim**
fixing #655 

Created another issue for the `errorDisplayed` https://github.com/zalando-incubator/atlas-ios/issues/675

[edit to ping zappr]

### CODE REVIEW

**Comment by hani-ibrahim** [comment]
👍

**Comment by bonkey** [comment]
👍

**Comment by bonkey** [comment]
Pretty green, but not yet :)

**Comment by bonkey** [comment]
👍

**Comment by bonkey** [comment]
👍

**Comment by hani-ibrahim** [comment]
merged in #675

**Pull request closed without merging**
