### PR TITLE
#39: Added parsing JSON array of models

### PR DESCRIPTION
**Pull request by bonkey**
- Addtional fetch with [Model] argument
- Removed AddressList

### CODE REVIEW

**Comment by bonkey** [comment]
@hani-ibrahim Maybe again my mind stuck, so if you have an idea how to merge two `fetch` funcs – you're welcome

**Comment by hani-ibrahim** [comment]
this is what I thought of 
```
func fetch<Model: JSONInitializable>(from endpoint: Endpoint,
           modelCompletion: (AtlasResult<Model> -> Void)? = nil,
           arrayCompletion: (AtlasResult<[Model]> -> Void)? = nil) {

    self.requestBuilders.createBuilder(forEndpoint: endpoint, urlSession: urlSession).execute { result in
        switch result {
        case .failure(let error):
            modelCompletion?(.failure(error))
            arrayCompletion?(.failure(error))
        case .success(let response):
            if let model = Model(json: response.body) {
                modelCompletion?(.success(model))
            } else if let jsons = response.body.array.flatMap({ $0 }) {
                let models = jsons.flatMap { Model(json: $0) }
                arrayCompletion?(.success(models))
            } else {
                modelCompletion?(.failure(AtlasAPIError.invalidResponseFormat))
                arrayCompletion?(.failure(AtlasAPIError.invalidResponseFormat))
            }
        }
    }
}
```
which I know is not good 😆

**Comment by bonkey** [comment]
👍

**Comment by hani-ibrahim** [comment]
👍

**Pull request merged**
