### PR TITLE
Removing .sharedInstance and adjust all related stuff

### PR DESCRIPTION
**Pull request by bonkey**
- Introduced Atlas struct with static func returning APIClient which will replace AtlasSDK and PublicAtlasSDK
- Marked AtlasSDK deprecated
- Adjusted Options to contain configurationURL

### CODE REVIEW

**Comment by bonkey** [comment]
👍

**Comment by bonkey** [comment]
*Please don't merge it alone.* First I'll merge here `issue-22` and maybe another some others related.

**Comment by bonkey** [comment]
👍

**Comment by ahmed-shehata** [comment]
👍

**Pull request merged**
