### PR TITLE
#277: Don't display "out of stock" sizes

### PR DESCRIPTION
**Pull request by artdaw**
#277: unavailable (out of stock) units are removed from Article

### CODE REVIEW

**Comment by bonkey** [comment]
👍

**Comment by artdaw** [comment]
👍

**Comment by bonkey** [comment]
👍

**Comment by hani-ibrahim** [comment]
@bonkey @artdaw 
I'm not sure if removing the out of stock sizes is the good approach
because first It's confusing for the use as that the user my think that you don't have this size at all and second this is not the behavior in the fashion store app 
img_2273

**Comment by artdaw** [comment]
@hani-ibrahim I also asked about it but AFAIK this is an agreement with Raphael

**Comment by ahmed-shehata** [comment]
👍

**Comment by artdaw** [comment]
👍

**Comment by bonkey** [comment]
@hani-ibrahim I agree with you – would prefer to have unavailable sizes as well, but
1. It was the requirement to hide them as @artdaw told
2. Main app has "notify me when available" for them where you subscribe to notification with your email

**Pull request merged**
