### PR TITLE
Configure Zappr

### PR DESCRIPTION
**Pull request by bonkey**
This is a reduced example of a [configuration file](https://zappr.readthedocs.io/en/latest/setup) for Zappr.
If you have questions you can reach us

  * in our [Gitter channel](https://gitter.im/zalando/zappr)
  * on [Twitter](https://twitter.com/zalando_zappr)

These are the features we currently support:

## Approvals

  * Approve pull requests with comments and configurable pattern
  * "Veto" (ie. block) pull requests with comments and configurable pattern
  * Configure how many approvals your pull request needs before merging
  * Extensively configure who can approve or veto in your project

## Pull Request guidelines

  * Block a PR until it has the required set of labels (e.g. `reviewed`)
  * Block a PR as long as it has unfinished tasks

## Specification guidelines

  * Configure minimum length of pull request title and description
  * Configure if pull request description can be the same as pull request template

## Commit message guidelines

  * Configure patterns that all commits in a pull request must match

## Automatic branch creation

  * Automatically create a branch in your repository for every issue

### CODE REVIEW

**Comment by bonkey** [comment]
I switched sth on https://zappr.opensource.zalan.do/repository/zalando-incubator/atlas-ios and it created this PR. Not sure if needed... I'll find out

**Comment by hani-ibrahim** [comment]
> Merging #677 into master will increase coverage by 0.51%
I started not feeling good about how this coverage is calculated 😟

**Comment by hani-ibrahim** [comment]
👍

**Comment by hani-ibrahim** [comment]
@bonkey merge/delete ?

**Comment by bonkey** [comment]
👍

**Comment by bonkey** [comment]
Doesn't help with

> zappr/pr/specification — Waiting for status to be reported

so kill it

**Pull request closed without merging**
