### PR TITLE
Migration to Swift3

### PR DESCRIPTION
**Pull request by bonkey**
OK, it's final for Swift 3, I'll take care of few other stuff, like `displayError...` and `process(force:...`) later on, I just want to merge it finally, not fine tune every single bit and be on 3.x all together.

### CODE REVIEW

**Comment by bonkey** [comment]
👍

**Comment by bonkey** [comment]
@hani-ibrahim I'm sorry, but I couldn't stand this global client: 2c43bff. I wanted to do the same for localizer, but tests are relying on `register`, so I'll reconsider it.

**Comment by hani-ibrahim** [comment]
👍

**Comment by hani-ibrahim** [comment]
👍

**Comment by hani-ibrahim** [comment]
@bonkey fixed small issues and the tests are now working local. You can merge it with it passes travis

**Comment by bonkey** [comment]
👍

**Comment by hani-ibrahim** [comment]
👍

**Pull request merged**
